export const FETCH_MY_SONGS = 'FETCH_MY_SONGS';
export const SEARCH_MY_SONGS = 'SEARCH_MY_SONGS';
export const SEARCH_YOUTUBE = 'SEARCH_YOUTUBE';
export const MY_SONG_SELECTED = 'MY_SONG_SELECTED';
export const YOUTUBE_SONG_SELECTED = 'YOUTUBE_SONG_SELECTED';
export const SAVE_TO_MY_LIST = 'SAVE_TO_MY_LIST';
export const REMOVE_FROM_MY_LIST = 'REMOVE_FROM_MY_LIST';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const REGISTER = 'REGISTER';

